language: node_js
node_js:
- '7'
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_ea4308d4c2d5_key -iv $encrypted_ea4308d4c2d5_iv
  -in id_rsa_deploy.enc -out ./.travis/id_rsa_deploy -d
- chmod 600 ~/.ssh/id_rsa_deploy
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_deploy
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'calebzhao'
- git config --global user.email 939347507@qq.com
install:
- npm install hexo-cli -g
- npm install
script: npm run deploy
cache:
  directories:
  - node_modules
