language: node_js
node_js:
- '10'
branches:
  only:
  - hexo

cache:
  directories:
    - node_modules

install:
- npm install hexo-cli -g
- npm install
# 执行清缓存，生成网页操作
script:
  - hexo clean
  - yuque-hexo sync
  - hexo generate
# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "939347507@qq.com"
  - git config user.email "939347507@qq.com"
  # 替换同目录下的_config.yml文件中GITHUB_TOKEN字符串为travis后台刚才配置的变量GITHUB_TOKEN，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/GITHUB_TOKEN/${GITHUB_TOKEN}/g" ./_config.yml
  - hexo deploy